# Ejercicios de Numpy

In [2]:
import numpy as np

In [17]:
# Creación de arrays: Crea un array unidimensional con los números del 0 al 9
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
# Array de ceros: Crea un array de 3x3 lleno de ceros
tam = (3,3)
np.zeros(tam)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# Array de unos: Crea un array de 2x4 lleno de unos
tam = (2,4)
np.ones(tam)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Array con rangos: Crea un array con valores del 10 al 25 con un paso de 2


In [4]:
# Array aleatorio: Crea un array de 5x5 con valores aleatorios entre 0 y 1

In [5]:
# Indexación: Dado el array arr = np.array([1,2,3,4,5]), seleccione el tercer elemento

In [6]:
# Slicing: Dado arr = np.arange(10), selcciona los elementos del índice 3 al 7

In [7]:
# Array bidimensional: Crea un array de 2x3 con valores enteros aleatorios entre 5 y 15

In [8]:
# Forma (shape): DAdo un array de 4x6, imprime su forma (shape)

In [9]:
# Redimensionar: Convierte un array unidimensional de 12 elementos en una matriz de 3x4

In [10]:
# Operaciones aritméticas: Dados dos arrays a = np.array([1,2,3]) y b = np.array([4,5,6]), calcula a+b, a*b y b-a

In [11]:
# Funciones universales: Calcula la raíz cuadrada de cada elemento en np.array([4,9,16,25])

In [12]:
# Boolean indexing: Dado arr = np.array([1,2,3,4,5]), crea un array booleano donde los valores mayores que 3 sean True

In [13]:
# Where: Usa np.where para reemplazar todos los valores impares en un array por -1

In [14]:
# Copiar arrays: Crea una copia independiente de un array (evitando la referencia en memoria)