# Ejercicios de Numpy

In [1]:
import numpy as np

In [17]:
# Creación de arrays: Crea un array unidimensional con los números del 0 al 9
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
# Array de ceros: Crea un array de 3x3 lleno de ceros
tam = (3,3)
np.zeros(tam)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# Array de unos: Crea un array de 2x4 lleno de unos
tam = (2,4)
np.ones(tam)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
# Array con rangos: Crea un array con valores del 10 al 25 con un paso de 2
arr = np.arange(10,26,2)
print(arr)

[10 12 14 16 18 20 22 24]


In [4]:
# Array aleatorio: Crea un array de 5x5 con valores aleatorios entre 0 y 1
arr = np.random.rand(5,5)
print(arr)

[[0.82944082 0.85196224 0.72193337 0.67746958 0.07339329]
 [0.8440612  0.81587861 0.62620274 0.88655916 0.10240447]
 [0.8345574  0.1927354  0.51460815 0.41640417 0.45421114]
 [0.62125225 0.83147226 0.34452587 0.28935444 0.47443422]
 [0.6231372  0.85212843 0.50221992 0.56774875 0.7966758 ]]


In [6]:
# Indexación: Dado el array arr = np.array([1,2,3,4,5]), seleccione el tercer elemento
arr = np.array([1,2,3,4,5])
print(arr[2])

3


In [7]:
# Slicing: Dado arr = np.arange(10), selcciona los elementos del índice 3 al 7
arr = np.arange(10)
print(arr[3:7])

[3 4 5 6]


In [8]:
# Array bidimensional: Crea un array de 2x3 con valores enteros aleatorios entre 5 y 15
arr = np.random.randint(5,16, size=(2,3))
print(arr)

[[ 5  6 11]
 [10  9  5]]


In [12]:
# Forma (shape): Dado un array de 4x6, imprime su forma (shape)
tam = (4,6)
arr = np.zeros(tam)
print(arr)
print(arr.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(4, 6)


In [13]:
# Redimensionar: Convierte un array unidimensional de 12 elementos en una matriz de 3x4
arr = np.arange(1,13)
print(arr)
arr = arr.reshape(3,4)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# Operaciones aritméticas: Dados dos arrays a = np.array([1,2,3]) y b = np.array([4,5,6]), calcula a+b, a*b y b-a
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(b-a)

[5 7 9]
[ 4 10 18]
[3 3 3]


In [15]:
# Funciones universales: Calcula la raíz cuadrada de cada elemento en np.array([4,9,16,25])
arr = np.array([4,9,16,25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [16]:
# Boolean indexing: Dado arr = np.array([1,2,3,4,5]), crea un array booleano donde los valores mayores que 3 sean True
arr = np.array([1,2,3,4,5])
res = arr > 3
print(res)

[False False False  True  True]


In [17]:
# Where: Usa np.where para reemplazar todos los valores impares en un array por -1
arr = np.array([1,2,3,4,5,6,7,8,9])
arrn = np.where(arr % 2 != 0, -1, arr)
print(arr)
print(arrn)

[1 2 3 4 5 6 7 8 9]
[-1  2 -1  4 -1  6 -1  8 -1]


In [18]:
# Copiar arrays: Crea una copia independiente de un array (evitando la referencia en memoria)
arr = np.array([1,2,3,4,5])
copia = np.copy(arr)
copia[0] = 99
print(arr)
print(copia)

[1 2 3 4 5]
[99  2  3  4  5]
